import CryptoKit
import Foundation

// GENERATED by Scripts/pin_model_hashes.sh — do not edit by hand.
//
// The speech model is downloaded at runtime rather than shipped inside the
// app (it is an order of magnitude larger than Blurt itself, and its licence
// is NVIDIA's to grant, not ours to redistribute). That download comes from a
// mutable branch on Hugging Face, so these hashes are what make it verifiable:
// Blurt refuses to load weights it was not built and tested against.
//
// `analytics/` is deliberately unpinned — Core ML writes its own bookkeeping
// there; it is not model content.
enum ModelIntegrity {

    /// Where the pinned files came from.
    static let modelRepository = "FluidInference/parakeet-tdt-0.6b-v3-coreml"
    static let pinnedOn = "2026-08-29"
    /// Approximate download size, for anything that tells the user.
    static let approximateMegabytes = 483

    /// Relative path inside the model directory → SHA-256.
    static let expected: [String: String] = [
        "Decoder.mlmodelc/coremldata.bin": "18647af085d87bd8f3121c8a9b4d4564c1ede038dab63d295b4e745cf2d7fb99",
        "Decoder.mlmodelc/metadata.json": "a39e93cd8371b8ded92635c7804fcd0590f0d1dd9415c6d19a0484be073077d9",
        "Decoder.mlmodelc/model.mil": "ef2a0a281695398a62fde86ac269c68f73d5b578d7ed3b31f2ba91a2d1ea1f35",
        "Decoder.mlmodelc/weights/weight.bin": "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41",
        "Encoder.mlmodelc/coremldata.bin": "d48034a167a82e88fc3df64f60af963ab3983538271175b8319e7d5720a0fb86",
        "Encoder.mlmodelc/metadata.json": "da24da9cca943fb29d7fa8e376d57fca7cb3aa08ca51b956b0b0e56813f087e9",
        "Encoder.mlmodelc/model.mil": "ed7b19156ca29fa7dfd6891deb9fda4b0e8893f68597c985d135736546a43808",
        "Encoder.mlmodelc/weights/weight.bin": "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421",
        "JointDecisionv3.mlmodelc/coremldata.bin": "f5fc08b741400f0088492c9e839418b1e18522f19cba28d361dd030c5f398342",
        "JointDecisionv3.mlmodelc/metadata.json": "d9307211b9a37e0f0ac260c7660b1571a3de25841035cfdf9b58fd40425f890f",
        "JointDecisionv3.mlmodelc/model.mil": "be60732943389a047175111a83f8839f3eb39d4803adafa828a0871b2f39818d",
        "JointDecisionv3.mlmodelc/weights/weight.bin": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
        "Preprocessor.mlmodelc/coremldata.bin": "dbde3f2300842c1fd51ef3ff948a0bcffe65ffd2dca10707f2509f32c1d65b1d",
        "Preprocessor.mlmodelc/metadata.json": "2a98699e22d279dd37fa1d238aeb1c6db1df0d6fad687775324157689d8f3acf",
        "Preprocessor.mlmodelc/model.mil": "4b8518a956450fec57f06c2a21bdffc26973f7f1fa6842fb38fe917f896b6b93",
        "Preprocessor.mlmodelc/weights/weight.bin": "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea",
        "config.json": "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
        "parakeet_v3_vocab.json": "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735",
        "parakeet_vocab.json": "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735",
    ]

    enum Verdict: Equatable {
        case verified
        /// Files whose contents differ from what this build expects.
        case mismatch([String])
        /// Files this build expects that are not on disk at all.
        case missing([String])

        var isTrustworthy: Bool { self == .verified }

        var explanation: String {
            switch self {
            case .verified:
                return "The speech model matches the version this build was tested with."
            case .mismatch(let files):
                return "The speech model on disk does not match the version this "
                    + "build of Blurt was tested with (\(files.count) file(s) differ). "
                    + "Blurt will not load it."
            case .missing(let files):
                return "The speech model is incomplete — \(files.count) file(s) are "
                    + "missing. Blurt will not load it."
            }
        }
    }

    /// Finds the directory that actually holds the model, since the SDK may
    /// hand back either the model directory or its parent.
    static func resolveModelDirectory(_ candidate: URL) -> URL {
        let marker = "Decoder.mlmodelc"
        if FileManager.default.fileExists(atPath: candidate.appendingPathComponent(marker).path) {
            return candidate
        }
        let nested = candidate.appendingPathComponent("parakeet-tdt-0.6b-v3")
        if FileManager.default.fileExists(atPath: nested.appendingPathComponent(marker).path) {
            return nested
        }
        return candidate
    }

    /// Checks every pinned file. Extra files are ignored: Core ML may add its
    /// own artifacts, and none of them change what the model computes.
    static func verify(modelDirectory: URL) -> Verdict {
        verifyAgainst(expected, modelDirectory: modelDirectory)
    }

    /// The same check against an explicit set of hashes — the seam the tests
    /// drive, so tamper detection is proven without a 480 MB fixture.
    static func verifyAgainst(
        _ expected: [String: String], modelDirectory: URL
    ) -> Verdict {
        let root = resolveModelDirectory(modelDirectory)
        var missing: [String] = []
        var mismatched: [String] = []

        for (relativePath, expectedHash) in expected {
            let url = root.appendingPathComponent(relativePath)
            guard let actual = sha256(of: url) else {
                missing.append(relativePath)
                continue
            }
            if actual != expectedHash { mismatched.append(relativePath) }
        }

        if !missing.isEmpty { return .missing(missing.sorted()) }
        if !mismatched.isEmpty { return .mismatch(mismatched.sorted()) }
        return .verified
    }

    /// Streams the file so a large weights blob never lands in memory at once.
    static func sha256(of url: URL) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }

        var hasher = SHA256()
        while true {
            guard let chunk = try? handle.read(upToCount: 4 * 1024 * 1024), !chunk.isEmpty
            else { break }
            hasher.update(data: chunk)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
