#!/bin/bash
# Regenerates Sources/Core/ModelIntegrity.swift from the speech model that is
# currently on this machine.
#
# Run this when deliberately adopting a new upstream model build — then run
# `make selftest` to confirm the new weights actually transcribe correctly
# BEFORE committing. The pinned hashes are what stop a silently changed
# upstream download from being loaded on users' machines.
#
# `analytics/` is excluded on purpose: Core ML writes its own bookkeeping
# there, so it is not model content and not stable to pin.
set -euo pipefail

cd "$(dirname "$0")/.."

MODEL_DIR="${1:-$HOME/Library/Application Support/FluidAudio/Models/parakeet-tdt-0.6b-v3}"
OUT="Sources/Core/ModelIntegrity.swift"

[[ -d "$MODEL_DIR" ]] || {
  echo "No model at: $MODEL_DIR"
  echo "Run 'make selftest' once to download it, then re-run this."
  exit 1
}

echo "==> Hashing $MODEL_DIR"
FILES=$(cd "$MODEL_DIR" && find . -type f -not -path "*/analytics/*" | sed 's|^\./||' | sort)
COUNT=$(echo "$FILES" | wc -l | tr -d ' ')
# The sum of the actual file bytes — that is the download, and MB here means
# decimal megabytes, which is what Finder and browsers show. (`du -h` would
# report MiB and read ~4% smaller.)
BYTES=$(cd "$MODEL_DIR" && find . -type f -not -path "*/analytics/*" -exec stat -f%z {} + \
  | awk '{s+=$1} END {print s}')
MB=$(( BYTES / 1000000 ))
echo "    $COUNT files, ${MB} MB"

{
  cat <<'HEADER'
import CryptoKit
import Foundation

// GENERATED by Scripts/pin_model_hashes.sh — do not edit by hand.
//
// The speech model is downloaded at runtime rather than shipped inside the
// app (it is an order of magnitude larger than Blurt itself, and its licence
// is NVIDIA's to grant, not ours to redistribute). That download comes from a
// mutable branch on Hugging Face, so these hashes are what make it verifiable:
// Blurt refuses to load weights it was not built and tested against.
//
// `analytics/` is deliberately unpinned — Core ML writes its own bookkeeping
// there; it is not model content.
enum ModelIntegrity {

HEADER

  echo "    /// Where the pinned files came from."
  echo "    static let modelRepository = \"FluidInference/parakeet-tdt-0.6b-v3-coreml\""
  echo "    static let pinnedOn = \"$(date -u +%Y-%m-%d)\""
  echo "    /// Approximate download size, for anything that tells the user."
  echo "    static let approximateMegabytes = $MB"
  echo ""
  echo "    /// Relative path inside the model directory → SHA-256."
  echo "    static let expected: [String: String] = ["

  while IFS= read -r file; do
    hash=$(shasum -a 256 "$MODEL_DIR/$file" | awk '{print $1}')
    echo "        \"$file\": \"$hash\","
  done <<< "$FILES"

  echo "    ]"
  cat <<'FOOTER'

    enum Verdict: Equatable {
        case verified
        /// Files whose contents differ from what this build expects.
        case mismatch([String])
        /// Files this build expects that are not on disk at all.
        case missing([String])

        var isTrustworthy: Bool { self == .verified }

        var explanation: String {
            switch self {
            case .verified:
                return "The speech model matches the version this build was tested with."
            case .mismatch(let files):
                return "The speech model on disk does not match the version this "
                    + "build of Blurt was tested with (\(files.count) file(s) differ). "
                    + "Blurt will not load it."
            case .missing(let files):
                return "The speech model is incomplete — \(files.count) file(s) are "
                    + "missing. Blurt will not load it."
            }
        }
    }

    /// Finds the directory that actually holds the model, since the SDK may
    /// hand back either the model directory or its parent.
    static func resolveModelDirectory(_ candidate: URL) -> URL {
        let marker = "Decoder.mlmodelc"
        if FileManager.default.fileExists(atPath: candidate.appendingPathComponent(marker).path) {
            return candidate
        }
        let nested = candidate.appendingPathComponent("parakeet-tdt-0.6b-v3")
        if FileManager.default.fileExists(atPath: nested.appendingPathComponent(marker).path) {
            return nested
        }
        return candidate
    }

    /// Checks every pinned file. Extra files are ignored: Core ML may add its
    /// own artifacts, and none of them change what the model computes.
    static func verify(modelDirectory: URL) -> Verdict {
        verifyAgainst(expected, modelDirectory: modelDirectory)
    }

    /// The same check against an explicit set of hashes — the seam the tests
    /// drive, so tamper detection is proven without a 480 MB fixture.
    static func verifyAgainst(
        _ expected: [String: String], modelDirectory: URL
    ) -> Verdict {
        let root = resolveModelDirectory(modelDirectory)
        var missing: [String] = []
        var mismatched: [String] = []

        for (relativePath, expectedHash) in expected {
            let url = root.appendingPathComponent(relativePath)
            guard let actual = sha256(of: url) else {
                missing.append(relativePath)
                continue
            }
            if actual != expectedHash { mismatched.append(relativePath) }
        }

        if !missing.isEmpty { return .missing(missing.sorted()) }
        if !mismatched.isEmpty { return .mismatch(mismatched.sorted()) }
        return .verified
    }

    /// Streams the file so a large weights blob never lands in memory at once.
    static func sha256(of url: URL) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }

        var hasher = SHA256()
        while true {
            guard let chunk = try? handle.read(upToCount: 4 * 1024 * 1024), !chunk.isEmpty
            else { break }
            hasher.update(data: chunk)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
FOOTER
} > "$OUT"

echo "==> Wrote $OUT"
echo "    Now run 'make selftest' to confirm these weights transcribe correctly."
